Add logger file

diff --git a/resources/templates/default/notify_postgresql.erb b/resources/templates/default/notify_postgresql.erb
--- a/resources/templates/default/notify_postgresql.erb
+++ b/resources/templates/default/notify_postgresql.erb
@@ -3,8 +3,14 @@
 IP_VIRTUAL=<%= @vip %>
 IFACE=<%= @iface %> 
 KEEPALIVED_CONF="/etc/keepalived/keepalived.conf"
+LOG_FILE="/var/log/rb_notify_master_postgresql.log"
 
-echo "Entering rb_notify_master_postgresql script with VIP: $IP_VIRTUAL"
+# Function for logging
+log() {
+  echo "$(date '+%Y-%m-%d %H:%M:%S') $1" | tee -a "$LOG_FILE"
+}
+
+log "Entering rb_notify_master_postgresql script with VIP: $IP_VIRTUAL"
 
 ################################
 # checking status section
@@ -13,9 +19,9 @@ echo "Entering rb_notify_master_postgresql script with VIP: $IP_VIRTUAL"
 grep "vrrp_sync_group vg_${IP_VIRTUAL}_postgresql {" $KEEPALIVED_CONF > /dev/null
 
 if [ $? -eq 0 ]; then
-  echo "The virtual IP $IP_VIRTUAL is registered in the vrrp_sync_group."
+  log "The virtual IP $IP_VIRTUAL is registered in the vrrp_sync_group."
 else
-  echo "Error: The virtual IP $IP_VIRTUAL is not registered in vrrp_sync_group."
+  log "Error: The virtual IP $IP_VIRTUAL is not registered in vrrp_sync_group."
   exit 1
 fi
 
@@ -23,16 +29,16 @@ SERF_OUTPUT=$(serf members -format=json -status=alive)
 MEMBER_COUNT=$(echo "$SERF_OUTPUT" | jq '.members | length')
 
 if [ "$MEMBER_COUNT" -gt 1 ]; then
-  echo "The cluster has $MEMBER_COUNT members so is OK."
+  log "The cluster has $MEMBER_COUNT members so is OK."
 else
-  echo "Error: There is only $MEMBER_COUNT member."
+  log "Error: There is only $MEMBER_COUNT member."
   exit 1
 fi
 
 if ip link show $IFACE | grep -q "state UP"; then
-  echo "The interface $IFACE is UP."
+  log "The interface $IFACE is UP."
 else
-  echo "The interface $IFACE is DOWN."
+  log "The interface $IFACE is DOWN."
   exit 1
 fi
 
@@ -42,9 +48,9 @@ fi
 
 sudo -u postgres psql -h 127.0.0.1 -c "select 1;" &>/dev/null
 if [ $? -eq 0 ]; then
-  echo "PostgreSQL connection is successful."
+  log "PostgreSQL connection is successful."
 else
-  echo "Failed to connect to PostgreSQL."
+  log "Failed to connect to PostgreSQL."
   exit 1
 fi
 
@@ -52,15 +58,17 @@ IS_RECOVERY=$(sudo -u postgres psql -h 127.0.0.1 -t -c "SELECT pg_is_in_recovery
 CURRENT_NODE=$(hostname -s)
 
 if [ "x$IS_RECOVERY" == "xt" ]; then
-  echo "The database is in recovery mode (Read-Only) on $CURRENT_NODE."
-
-  rb_sync_from_master.sh $CURRENT_NODE
-else
-  echo "The database is not in recovery mode (Read-Write) on $CURRENT_NODE."
+  log "The database is in recovery mode (Read-Only) on $CURRENT_NODE. Sleeping for 30 sec..."
+  sleep 30
   touch /tmp/postgresql.trigger
-fi
+  sed -i '/^primary_conninfo/d' /var/lib/pgsql/data/postgresql.conf
+  sed -i '/^promote_trigger_file/d' /var/lib/pgsql/data/postgresql.conf
+else
+  log "The database is not in recovery mode (Read-Write) on $CURRENT_NODE."
+  rb_sync_from_master.sh $CURRENT_NODE
 
-echo "Updating /etc/hosts"
-sed -i 's/.*postgresql.*//g' /etc/hosts
-sudo sed -i '/^$/d' /etc/hosts
-echo "$IP_VIRTUAL master.postgresql.service" >> /etc/hosts
+  if [ $? -ne 0 ]; then
+    log "rb_sync_from_master.sh failed."
+    exit 1
+  fi
+fi
